export const translations = {
  fr: {
    home: "Accueil",
    flights: "Vols",
    procedures: "Procédures",
    evisas: "E-Visa",
    resources: "Ressources",
    guidePdf: "Guide PDF",
    quickEval: "Évaluation Rapide",
    trackDossier: "Suivi de dossier",
    clientAccess: "Accès Client",
    createAccount: "Créer un compte",
    darkMode: "Sombre",
    lightMode: "Clair",
    systemMode: "Système",
    heroBadge: "Évaluation Gratuite en 24h : Votre Passeport pour le Monde !",
    heroTitle: "Votre Avenir Commence Ici :",
    heroHighlight: "Visa & Immigration Simplifiés",
    heroDesc: "Découvrez les meilleures opportunités de mobilité internationale. Remplissez notre formulaire gratuit et laissez nos experts vous guider vers votre projet d'études, de travail ou d'immigration.",
    startEval: "Démarrer mon Évaluation",
    chatExpert: "Discuter avec un Expert (WhatsApp)",
    statsSuccess: "Dossiers Traités avec Succès",
    statsClients: "Clients Satisfaits",
    statsGuarantee: "Réponse Garantie",
    downloadGuideEn: "Download English PDF Guide",
  },
  en: {
    home: "Home",
    flights: "Flights",
    procedures: "Procedures",
    evisas: "E-Visa",
    resources: "Resources",
    guidePdf: "PDF Guide",
    quickEval: "Quick Evaluation",
    trackDossier: "Track Dossier",
    clientAccess: "Client Access",
    createAccount: "Create Account",
    darkMode: "Dark",
    lightMode: "Light",
    systemMode: "System",
    heroBadge: "Free 24h Evaluation: Your Passport to the World!",
    heroTitle: "Your Future Starts Here:",
    heroHighlight: "Simplified Visa & Immigration",
    heroDesc: "Discover the best international mobility opportunities. Fill out our free form and let our experts guide you toward your study, work, or immigration project.",
    startEval: "Start My Evaluation",
    chatExpert: "Chat with an Expert (WhatsApp)",
    statsSuccess: "Successfully Processed Files",
    statsClients: "Satisfied Clients",
    statsGuarantee: "Guaranteed Response",
    downloadGuideEn: "Download English PDF Guide",
  }
};
