CREATE TABLE `applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dossierNumber` varchar(20) NOT NULL,
	`candidateId` int,
	`fullName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`whatsappNumber` varchar(50) NOT NULL,
	`age` int,
	`nationality` varchar(100),
	`academicLevel` varchar(100),
	`experienceYears` int,
	`languageSkills` varchar(255),
	`jobSector` varchar(100),
	`destination` enum('canada','luxembourg','pologne','europe','golfe','oceanie','caucase','autre') NOT NULL,
	`formulaChosen` enum('integral','echelonne','garanti') NOT NULL DEFAULT 'integral',
	`documentsUrls` text,
	`paymentStatus` enum('PENDING','SUCCESS','FAILED','CANCELLED') NOT NULL DEFAULT 'PENDING',
	`paymentTransactionId` varchar(255),
	`paymentAmount` int NOT NULL DEFAULT 65000,
	`paymentCurrency` varchar(10) NOT NULL DEFAULT 'XAF',
	`paymentMethod` varchar(50),
	`paymentDate` timestamp,
	`dossierStatus` enum('nouveau','paye','en_cours','documents_requis','soumis','approuve','refuse') NOT NULL DEFAULT 'nouveau',
	`adminNote` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `applications_id` PRIMARY KEY(`id`),
	CONSTRAINT `applications_dossierNumber_unique` UNIQUE(`dossierNumber`)
);
