CREATE TABLE `profile_evaluations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`destination` varchar(100) NOT NULL,
	`projectType` enum('student','visitor','worker','permanent_residence','family_reunification','other') NOT NULL,
	`currentCountry` varchar(100),
	`communicationLanguage` enum('fr','en') DEFAULT 'fr',
	`fullName` varchar(255) NOT NULL,
	`gender` enum('homme','femme','autre'),
	`dateOfBirth` varchar(20),
	`placeOfBirth` varchar(150),
	`nationality` varchar(100),
	`currentAddress` text,
	`whatsappPhone` varchar(50) NOT NULL,
	`email` varchar(320) NOT NULL,
	`passportNumber` varchar(50),
	`passportCountry` varchar(100),
	`passportIssueDate` varchar(20),
	`passportExpiryDate` varchar(20),
	`passportCopyAvailable` boolean DEFAULT false,
	`oldPassportAvailable` boolean DEFAULT false,
	`idCardAvailable` boolean DEFAULT false,
	`maritalStatus` enum('single','married','divorced','widowed','civil_union'),
	`spouseName` varchar(255),
	`numberOfChildren` int DEFAULT 0,
	`dependents` int DEFAULT 0,
	`familyInDestination` boolean DEFAULT false,
	`familyMemberRelation` varchar(100),
	`familyMemberStatus` varchar(100),
	`educationLevel` varchar(100),
	`latestDiploma` varchar(255),
	`fieldOfStudy` varchar(150),
	`diplomaYear` int,
	`institution` varchar(255),
	`diplomasAvailable` boolean DEFAULT false,
	`currentProfession` varchar(150),
	`currentEmployer` varchar(255),
	`yearsOfExperience` int,
	`previousExperiences` text,
	`monthlyIncome` int,
	`cvAvailable` boolean DEFAULT false,
	`jobOfferAvailable` boolean DEFAULT false,
	`bankBalance` int,
	`bankBalanceAverage6Months` int,
	`hasSponsor` boolean DEFAULT false,
	`sponsorName` varchar(255),
	`fundSource` varchar(100),
	`realEstate` boolean DEFAULT false,
	`businessActivity` boolean DEFAULT false,
	`debts` boolean DEFAULT false,
	`countriesVisited` text,
	`visasObtained` text,
	`visaRefusals` boolean DEFAULT false,
	`overstayHistory` boolean DEFAULT false,
	`deportationOrRefusal` boolean DEFAULT false,
	`previousApplications` text,
	`criminalRecord` boolean DEFAULT false,
	`immigrationIssues` boolean DEFAULT false,
	`medicalConcerns` boolean DEFAULT false,
	`falseDeclaration` boolean DEFAULT false,
	`specialNeeds` text,
	`documentsAvailable` text,
	`desiredProgram` varchar(255),
	`desiredEducationLevel` varchar(100),
	`targetInstitution` varchar(255),
	`admissionLetterAvailable` boolean DEFAULT false,
	`intendedStartDate` varchar(20),
	`studyBudget` int,
	`studyFunder` varchar(100),
	`academicProject` text,
	`postStudiesProject` text,
	`companions` text,
	`visitReason` varchar(100),
	`visitType` enum('tourism','family','business','event','other'),
	`plannedStayDuration` varchar(50),
	`estimatedTravelDate` varchar(20),
	`plannedAccommodation` varchar(100),
	`invitingPerson` varchar(255),
	`invitationLetterAvailable` boolean DEFAULT false,
	`stayFunder` varchar(100),
	`tiesInHomeCountry` text,
	`desiredPosition` varchar(150),
	`targetCity` varchar(100),
	`relatedExperience` int,
	`relatedDiplomas` text,
	`languageLevel` varchar(50),
	`departureAvailability` varchar(50),
	`targetCategory` varchar(100),
	`age` int,
	`ecaAvailable` boolean DEFAULT false,
	`experienceYears` int,
	`experienceInDestination` boolean DEFAULT false,
	`provincialNomination` boolean DEFAULT false,
	`availableFunds` int,
	`policeCertificatesAvailable` boolean DEFAULT false,
	`status` enum('draft','submitted','reviewed','contacted','closed') NOT NULL DEFAULT 'submitted',
	`submissionNotes` text,
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `profile_evaluations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `applications` ADD `agreementSigned` boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE `applications` ADD `agreementSignedAt` int;--> statement-breakpoint
ALTER TABLE `applications` ADD `agreementSignatureName` varchar(255);--> statement-breakpoint
ALTER TABLE `applications` ADD `agreementIpAddress` varchar(64);