CREATE TABLE `application_status_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int NOT NULL,
	`previousStatus` varchar(50) NOT NULL,
	`newStatus` varchar(50) NOT NULL,
	`changedBy` varchar(320),
	`reason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `application_status_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `automated_tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int NOT NULL,
	`taskType` enum('send_email','send_whatsapp','request_documents','follow_up','payment_reminder','evaluation_reminder','auto_approve','auto_reject') NOT NULL,
	`status` enum('pending','in_progress','completed','failed','cancelled') NOT NULL DEFAULT 'pending',
	`scheduledFor` timestamp NOT NULL,
	`executedAt` timestamp,
	`failureReason` text,
	`retryCount` int DEFAULT 0,
	`maxRetries` int DEFAULT 3,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `automated_tasks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `candidate_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationNumber` varchar(50) NOT NULL,
	`candidateId` int,
	`fullName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`whatsappNumber` varchar(50),
	`destination` varchar(100) NOT NULL,
	`visaType` varchar(100) NOT NULL,
	`educationLevel` varchar(100),
	`experienceYears` int,
	`languageSkills` varchar(255),
	`scoringTotal` int,
	`scoringDetails` text,
	`scoringBadge` enum('excellent','bon','moyen','faible'),
	`status` enum('nouveau','en_evaluation','documents_requis','en_attente','approuve','refuse','archive') NOT NULL DEFAULT 'nouveau',
	`paymentStatus` enum('non_paye','en_attente','paye','remboursement') NOT NULL DEFAULT 'non_paye',
	`paymentAmount` int,
	`paymentDate` timestamp,
	`documentsCount` int DEFAULT 0,
	`documentsUrls` text,
	`emailSent` boolean DEFAULT false,
	`whatsappSent` boolean DEFAULT false,
	`lastEmailSentAt` timestamp,
	`lastWhatsappSentAt` timestamp,
	`adminNotes` text,
	`internalNotes` text,
	`evaluationCompletedAt` timestamp,
	`approvedAt` timestamp,
	`rejectedAt` timestamp,
	`rejectionReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`nextFollowUpAt` timestamp,
	CONSTRAINT `candidate_applications_id` PRIMARY KEY(`id`),
	CONSTRAINT `candidate_applications_applicationNumber_unique` UNIQUE(`applicationNumber`)
);
