CREATE TABLE `evisas` (
`id` int AUTO_INCREMENT NOT NULL,
`countryCode` varchar(3) NOT NULL,
`countryName` varchar(100) NOT NULL,
`countryFlag` varchar(10),
`continent` varchar(50) NOT NULL,
`region` varchar(100),
`description` text,
`evisaType` varchar(100) NOT NULL,
`visaFee` int NOT NULL DEFAULT 0,
`accompanimentFee` int NOT NULL DEFAULT 25000,
`totalCost` int NOT NULL DEFAULT 25000,
`currency` varchar(10) NOT NULL DEFAULT 'XOF',
`processingTime` varchar(100) NOT NULL,
`validity` varchar(100) NOT NULL,
`stayDuration` varchar(100),
`requirements` text,
`documents` text,
`eligibility` text,
`restrictions` text,
`advantages` text,
`additionalInfo` text,
`isActive` boolean NOT NULL DEFAULT true,
`isPopular` boolean NOT NULL DEFAULT false,
`lastUpdatedBy` varchar(255),
`aiGenerated` boolean NOT NULL DEFAULT false,
`createdAt` timestamp NOT NULL DEFAULT (now()),
`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT `evisas_id` PRIMARY KEY(`id`),
CONSTRAINT `evisas_countryCode_unique` UNIQUE(`countryCode`)
);
