CREATE TABLE IF NOT EXISTS `hotel_catalog` (
  `id` int AUTO_INCREMENT NOT NULL,
  `source` enum('openstreetmap','official','manual') NOT NULL DEFAULT 'openstreetmap',
  `sourceId` varchar(120) NOT NULL,
  `sourceUrl` text,
  `sourceAttribution` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `country` varchar(100) NOT NULL,
  `city` varchar(120) NOT NULL,
  `address` text,
  `latitude` decimal(10,7),
  `longitude` decimal(10,7),
  `officialWebsiteUrl` text,
  `officialBookingUrl` text,
  `phone` varchar(80),
  `stars` int,
  `amenitiesJson` text,
  `verificationStatus` enum('imported','verified','inactive') NOT NULL DEFAULT 'imported',
  `lastImportedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastVerifiedAt` timestamp NULL,
  `verifiedByAdminEmail` varchar(320),
  `rawSourceJson` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `hotel_catalog_id` PRIMARY KEY(`id`),
  CONSTRAINT `hotel_catalog_sourceId_unique` UNIQUE(`sourceId`),
  KEY `idx_hotel_catalog_country_city_status` (`country`,`city`,`verificationStatus`)
);
