CREATE TABLE email_delivery_advisor_thresholds (
  id INT AUTO_INCREMENT PRIMARY KEY,
  advisorEmail VARCHAR(320) NOT NULL UNIQUE,
  dailyFailureThreshold INT NOT NULL DEFAULT 3,
  updatedByAdminEmail VARCHAR(320) NOT NULL,
  lastAlertedAt TIMESTAMP NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
