import { CalendarRange, CircleDollarSign, PlaneTakeoff, ShieldCheck, Ticket, Users } from "lucide-react";
import { Link } from "wouter";
import { ServicePageShell, ServiceSection } from "@/components/ServicePageShell";

export default function Billets() {
  return <ServicePageShell eyebrow="Billets d’avion · Recherche et accompagnement" title="Recherchez un billet adapté à votre itinéraire" introduction="Comparez votre projet de voyage, préparez une demande de devis et poursuivez avec l’équipe 3M Travel lorsque vous souhaitez une assistance de réservation." primaryHref="/flights" primaryLabel="Rechercher mon billet" notice="Offre promotionnelle annoncée : jusqu’à -20 % sur une sélection et selon les conditions tarifaires applicables. Les disponibilités, taxes, règles de modification et prix finaux doivent être confirmés avant émission.">
    <ServiceSection title="Un seul moteur de réservation, plusieurs services" introduction="La page Billets oriente vers le moteur de recherche existant : aucun moteur concurrent n’est créé."><div className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border p-6"><PlaneTakeoff className="h-7 w-7 text-blue-700" /><h3 className="mt-4 font-black">Itinéraire</h3><p className="mt-2 text-sm leading-6 text-slate-600">Aller simple, aller-retour ou parcours multi-destinations selon votre besoin.</p></article><article className="rounded-2xl border p-6"><CircleDollarSign className="h-7 w-7 text-blue-700" /><h3 className="mt-4 font-black">Prix à confirmer</h3><p className="mt-2 text-sm leading-6 text-slate-600">Le tarif et les conditions sont vérifiés au moment de la réservation, avant toute émission.</p></article><article className="rounded-2xl border p-6"><ShieldCheck className="h-7 w-7 text-blue-700" /><h3 className="mt-4 font-black">Suivi de réservation</h3><p className="mt-2 text-sm leading-6 text-slate-600">Après traitement, les documents de voyage sont synchronisés dans l’espace client et par e-mail.</p></article></div></ServiceSection>
    <ServiceSection tone="blue" title="Avant de demander votre devis"><div className="grid gap-4 md:grid-cols-3"><p className="rounded-xl bg-white p-5 text-sm text-slate-700"><CalendarRange className="mb-3 h-5 w-5 text-blue-700" />Dates de voyage et flexibilité éventuelle.</p><p className="rounded-xl bg-white p-5 text-sm text-slate-700"><Users className="mb-3 h-5 w-5 text-blue-700" />Nombre de voyageurs et catégorie de cabine souhaitée.</p><p className="rounded-xl bg-white p-5 text-sm text-slate-700"><Ticket className="mb-3 h-5 w-5 text-blue-700" />Ville de départ, destination et contraintes de bagages.</p></div><div className="mt-8"><Link href="/flights" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-blue-700 px-5 py-3 text-sm font-black text-white hover:bg-blue-800">Accéder au moteur de vols</Link></div></ServiceSection>
  </ServicePageShell>;
}
