import { ArrowUpRight, BookOpen, CalendarClock, ExternalLink, Landmark, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const resources = [
  { title: "Canada : comprendre les parcours de résidence permanente", description: "Repères sur Entrée express, les programmes provinciaux, les programmes régionaux, le parrainage familial et les voies québécoises. Les critères applicables doivent être confirmés auprès d’IRCC.", href: "/canada", label: "Lire le guide Canada", icon: Landmark, kind: "Guide 3M" },
  { title: "Schengen : préparer un séjour de courte durée", description: "Tourisme, affaires, visite familiale, soins, événement ou transit : le motif du voyage et le consulat compétent déterminent les pièces utiles.", href: "/schengen", label: "Lire le guide Schengen", icon: BookOpen, kind: "Guide 3M" },
  { title: "Règles générales du visa Schengen", description: "La Commission européenne présente les règles de court séjour, les entrées simples ou multiples et le transit aéroportuaire. Les séjours longs suivent une procédure nationale.", href: "https://home-affairs.ec.europa.eu/policies/schengen/visa-policy/applying-schengen-visa_en", label: "Consulter la source officielle", icon: ShieldCheck, kind: "Source officielle", external: true },
  { title: "Programmes de résidence permanente au Canada", description: "IRCC maintient la liste des voies disponibles, suspendues ou fermées. Consultez la source officielle avant toute décision et avant de préparer un dossier.", href: "https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada.html", label: "Consulter IRCC", icon: CalendarClock, kind: "Source officielle", external: true },
];

export default function Blog() {
  return <main className="min-h-screen bg-slate-50 px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><header className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.18em] text-blue-700">Ressources et actualités à vérifier</p><h1 className="mt-4 text-4xl font-black tracking-tight text-slate-950 sm:text-5xl">Le centre d’information 3M Travel</h1><p className="mt-5 text-base leading-7 text-slate-600">Des repères utiles pour préparer un projet de mobilité internationale. Les règles et disponibilités peuvent évoluer : les liens officiels restent la référence avant toute démarche.</p></header><section className="mt-12 grid gap-5 md:grid-cols-2">{resources.map((resource) => { const Icon = resource.icon; const content = <><div className="flex items-start justify-between gap-4"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-800">{resource.kind}</span><Icon className="h-6 w-6 text-blue-700" aria-hidden="true" /></div><h2 className="mt-6 text-xl font-black text-slate-950">{resource.title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{resource.description}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-black text-blue-700">{resource.label}{resource.external ? <ExternalLink className="h-4 w-4" /> : <ArrowUpRight className="h-4 w-4" />}</span></>; return resource.external ? <a key={resource.title} href={resource.href} target="_blank" rel="noopener noreferrer" className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md">{content}</a> : <Link key={resource.title} href={resource.href} className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md">{content}</Link>; })}</section><section className="mt-12 rounded-2xl bg-blue-800 p-8 text-white"><h2 className="text-2xl font-black">Vous avez besoin d’une orientation adaptée ?</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-blue-100">Commencez par une évaluation de votre profil afin de clarifier les informations à préparer et les voies à explorer selon votre situation.</p><Link href="/evaluation" className="mt-6 inline-flex min-h-11 items-center rounded-xl bg-white px-5 py-3 text-sm font-black text-blue-900 hover:bg-blue-50">Faire évaluer mon profil</Link></section></div></main>;
}
