import { Download, FileText, RefreshCw, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";

const labels: Record<string, string> = { nouveau: "Dossier créé", en_evaluation: "Évaluation en cours", bilan_envoye: "Bilan envoyé", en_attente_paiement: "Paiement en attente", paye: "Paiement confirmé", en_attente_documents: "Documents requis", documents_recus: "Documents reçus", en_cours_traitement: "Dossier en traitement", soumis: "Dossier soumis", approuve: "Dossier approuvé", visa_approuve: "Visa approuvé" };
const progressFor = (status: string) => Math.min(100, Math.max(10, ({ nouveau: 10, en_evaluation: 20, bilan_envoye: 30, en_attente_paiement: 40, paye: 50, en_attente_documents: 60, documents_recus: 70, en_cours_traitement: 80, soumis: 90, approuve: 100, visa_approuve: 100 } as Record<string, number>)[status] ?? 10));

export default function ClientCaseTracking() {
  const utils = trpc.useUtils();
  const tracking = trpc.caseTracking.getMyCases.useQuery(undefined, { retry: false });
  const insurance = trpc.caseTracking.getMyInsuranceRequests.useQuery(undefined, { retry: false });
  const refresh = async () => { await Promise.all([utils.caseTracking.getMyCases.invalidate(), utils.caseTracking.getMyInsuranceRequests.invalidate()]); toast.success("Vos informations ont été actualisées."); };
  const downloadDocument = async (id: number) => { try { const result = await utils.caseTracking.downloadMyDocument.fetch({ documentId: id }); window.open(result.url, "_blank", "noopener,noreferrer"); } catch { toast.error("Document indisponible."); } };
  const downloadAttestation = async (id: number) => { try { const result = await utils.caseTracking.downloadMyInsuranceAttestation.fetch({ insuranceRequestId: id }); window.open(result.url, "_blank", "noopener,noreferrer"); } catch { toast.error("Attestation indisponible."); } };
  const loading = tracking.isLoading || insurance.isLoading;

  return <main className="min-h-screen bg-slate-50 pt-24 pb-16"><div className="container max-w-6xl space-y-6">
    <section className="rounded-3xl bg-gradient-to-br from-[#052b56] to-[#0b5ca8] p-7 text-white shadow-xl"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="flex items-center gap-2 text-sm text-blue-100"><ShieldCheck className="h-4 w-4" /> Espace client sécurisé</p><h1 className="mt-2 text-3xl font-bold">Suivi de mes dossiers</h1><p className="mt-2 text-blue-100">Consultez vos étapes, documents et attestations depuis un seul espace.</p></div><Button variant="secondary" onClick={refresh} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} />Actualiser</Button></div></section>
    {tracking.isError ? <Card className="border-amber-200 bg-amber-50"><CardContent className="p-6"><p className="font-semibold">Connexion candidate requise</p><p className="mt-1 text-sm">Connectez-vous pour voir exclusivement les dossiers associés à votre compte.</p><Button asChild className="mt-4"><Link href="/login">Se connecter</Link></Button></CardContent></Card> : null}
    <section className="grid gap-4 md:grid-cols-3"><Card><CardContent className="p-5"><p className="text-2xl font-bold">{tracking.data?.cases.length ?? 0}</p><p className="text-sm text-muted-foreground">Dossiers suivis</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-2xl font-bold">{tracking.data?.unreadNotifications ?? 0}</p><p className="text-sm text-muted-foreground">Notifications non lues</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">Actualisation manuelle</p><p className="font-semibold">À la demande</p></CardContent></Card></section>
    <section className="space-y-4"><div><h2 className="text-xl font-bold">Mes dossiers</h2><p className="text-sm text-muted-foreground">Les informations sont filtrées par votre identité candidate côté serveur.</p></div>{loading ? <Card><CardContent className="p-8 text-center text-muted-foreground">Chargement…</CardContent></Card> : null}{!loading && !tracking.data?.cases.length ? <Card><CardContent className="p-8 text-center"><FileText className="mx-auto h-10 w-10 text-blue-700" /><p className="mt-3 font-semibold">Aucun dossier associé à votre compte</p><Button asChild className="mt-4"><Link href="/evaluation">Lancer une évaluation</Link></Button></CardContent></Card> : null}{tracking.data?.cases.map(item => <Card key={item.id}><CardHeader><div className="flex flex-col gap-2 md:flex-row md:justify-between"><div><CardTitle>{item.caseNumber}</CardTitle><CardDescription>{item.countryTarget || "Destination à confirmer"} · {item.visaType || item.caseType || "Procédure"}</CardDescription></div><Badge className="w-fit">{labels[item.currentStatus] || item.currentStatus}</Badge></div></CardHeader><CardContent className="space-y-4"><div><div className="mb-2 flex justify-between text-sm"><span>Avancement</span><span>{progressFor(item.currentStatus)}%</span></div><Progress value={progressFor(item.currentStatus)} /></div><p className="text-sm"><strong>Documents :</strong> {item.requirements.filter(req => ["received", "approved", "waived"].includes(req.status)).length}/{item.requirements.length || 0} traités</p>{item.documents.length ? <div className="flex flex-wrap gap-2">{item.documents.map(doc => <Button key={doc.id} variant="outline" size="sm" onClick={() => downloadDocument(doc.id)}><Download className="mr-2 h-3.5 w-3.5" />{doc.fileName}</Button>)}</div> : null}</CardContent></Card>)}</section>
    <section className="space-y-4"><div><h2 className="text-xl font-bold">Mes assurances voyage</h2><p className="text-sm text-muted-foreground">Votre attestation devient disponible dès sa finalisation par l’agence.</p></div>{insurance.data?.length ? <div className="grid gap-4 md:grid-cols-2">{insurance.data.map(item => <Card key={item.id}><CardContent className="space-y-3 p-5"><div className="flex justify-between gap-2"><div><p className="font-semibold">{item.reference}</p><p className="text-sm text-muted-foreground">{item.destinationCountry} · {item.coveragePlan}</p></div><Badge variant="outline">{item.status}</Badge></div>{item.attestationFileName ? <Button className="w-full" onClick={() => downloadAttestation(item.id)}><Download className="mr-2 h-4 w-4" />Télécharger l’attestation</Button> : <p className="text-sm text-muted-foreground">Attestation en attente de finalisation.</p>}</CardContent></Card>)}</div> : <Card><CardContent className="p-5 text-sm text-muted-foreground">Aucune demande d’assurance associée à ce compte.</CardContent></Card>}</section>
  </div></main>;
}
