-- Baseline additive for canonical case tracking.
-- Applied manually on 2026-08-12 after review; retained for repository traceability.
CREATE TABLE IF NOT EXISTS `cases` (`id` INT AUTO_INCREMENT PRIMARY KEY, `caseNumber` VARCHAR(32) NOT NULL UNIQUE, `candidateId` INT NULL, `legacyApplicationId` INT NULL UNIQUE, `legacyAgencyDossierId` INT NULL UNIQUE, `sourceChannel` ENUM('online','agency_manual','whatsapp','email') NOT NULL, `countryTarget` VARCHAR(100) NULL, `caseType` VARCHAR(80) NULL, `visaType` VARCHAR(100) NULL, `currentStatus` VARCHAR(80) NOT NULL DEFAULT 'nouveau', `assignedAdminId` INT NULL, `priority` ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal', `openedAt` TIMESTAMP NULL, `closedAt` TIMESTAMP NULL, `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX `idx_cases_candidate_status` (`candidateId`,`currentStatus`), INDEX `idx_cases_assignee_status` (`assignedAdminId`,`currentStatus`));
CREATE TABLE IF NOT EXISTS `case_applicants` (`id` INT AUTO_INCREMENT PRIMARY KEY, `caseId` INT NOT NULL, `relationshipType` VARCHAR(80) NOT NULL DEFAULT 'principal', `fullName` VARCHAR(255) NOT NULL, `dateOfBirth` DATE NULL, `nationality` VARCHAR(100) NULL, `passportNumber` VARCHAR(64) NULL, `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX `idx_case_applicants_case` (`caseId`));
CREATE TABLE IF NOT EXISTS `case_documents` (`id` INT AUTO_INCREMENT PRIMARY KEY, `caseId` INT NOT NULL, `candidateId` INT NULL, `legacyCandidateFileId` INT NULL UNIQUE, `documentType` VARCHAR(100) NOT NULL, `fileName` VARCHAR(255) NOT NULL, `fileKey` VARCHAR(512) NULL, `mimeType` VARCHAR(100) NULL, `fileSizeBytes` INT NULL, `uploadedByRole` ENUM('candidate','admin','agency') NOT NULL, `reviewStatus` ENUM('received','pending','approved','rejected','correction_required') NOT NULL DEFAULT 'received', `reviewNote` TEXT NULL, `versionNo` INT NOT NULL DEFAULT 1, `uploadedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `reviewedAt` TIMESTAMP NULL, INDEX `idx_case_documents_case_status` (`caseId`,`reviewStatus`), INDEX `idx_case_documents_candidate` (`candidateId`));
CREATE TABLE IF NOT EXISTS `document_requirements` (`id` INT AUTO_INCREMENT PRIMARY KEY, `caseId` INT NOT NULL, `documentType` VARCHAR(100) NOT NULL, `isRequired` BOOLEAN NOT NULL DEFAULT TRUE, `status` ENUM('pending','received','approved','rejected','waived') NOT NULL DEFAULT 'pending', `dueAt` TIMESTAMP NULL, `requestedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `validatedAt` TIMESTAMP NULL, `rejectedAt` TIMESTAMP NULL, `adminComment` TEXT NULL, INDEX `idx_document_requirements_case_status` (`caseId`,`status`));
CREATE TABLE IF NOT EXISTS `case_status_history` (`id` INT AUTO_INCREMENT PRIMARY KEY, `caseId` INT NOT NULL, `oldStatus` VARCHAR(80) NULL, `newStatus` VARCHAR(80) NOT NULL, `changedByRole` ENUM('candidate','admin','system') NOT NULL, `changedById` INT NULL, `comment` TEXT NULL, `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX `idx_case_status_history_case_created` (`caseId`,`createdAt`));
CREATE TABLE IF NOT EXISTS `client_notifications` (`id` INT AUTO_INCREMENT PRIMARY KEY, `candidateId` INT NOT NULL, `caseId` INT NULL, `type` VARCHAR(80) NOT NULL, `title` VARCHAR(255) NOT NULL, `body` TEXT NOT NULL, `actionUrl` VARCHAR(512) NULL, `isRead` BOOLEAN NOT NULL DEFAULT FALSE, `emailSentAt` TIMESTAMP NULL, `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX `idx_client_notifications_candidate_read` (`candidateId`,`isRead`));
CREATE TABLE IF NOT EXISTS `case_tasks` (`id` INT AUTO_INCREMENT PRIMARY KEY, `caseId` INT NOT NULL, `title` VARCHAR(255) NOT NULL, `description` TEXT NULL, `assignedAdminId` INT NULL, `dueAt` TIMESTAMP NULL, `taskStatus` ENUM('open','in_progress','completed','cancelled') NOT NULL DEFAULT 'open', `createdByAdminId` INT NULL, `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX `idx_case_tasks_assignee_status` (`assignedAdminId`,`taskStatus`));
CREATE TABLE IF NOT EXISTS `case_admin_notes` (`id` INT AUTO_INCREMENT PRIMARY KEY, `caseId` INT NOT NULL, `adminId` INT NULL, `note` TEXT NOT NULL, `isPrivate` BOOLEAN NOT NULL DEFAULT TRUE, `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX `idx_case_admin_notes_case_created` (`caseId`,`createdAt`));
CREATE TABLE IF NOT EXISTS `case_activity_logs` (`id` INT AUTO_INCREMENT PRIMARY KEY, `caseId` INT NOT NULL, `actorRole` ENUM('candidate','admin','system') NOT NULL, `actorId` INT NULL, `actionType` VARCHAR(100) NOT NULL, `entityType` VARCHAR(100) NOT NULL, `entityId` VARCHAR(100) NULL, `description` TEXT NULL, `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX `idx_case_activity_logs_case_created` (`caseId`,`createdAt`));
