CREATE TABLE IF NOT EXISTS `tourism_service_requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reference` VARCHAR(32) NOT NULL,
  `fullName` VARCHAR(255) NOT NULL,
  `email` VARCHAR(320) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `destination` VARCHAR(160) NOT NULL,
  `departureDate` DATE NULL,
  `returnDate` DATE NULL,
  `travelersCount` INT NOT NULL DEFAULT 1,
  `serviceTypesJson` TEXT NOT NULL,
  `packType` VARCHAR(80) NULL,
  `hotelCategory` VARCHAR(80) NULL,
  `vehicleCategory` VARCHAR(80) NULL,
  `pickupLocation` VARCHAR(255) NULL,
  `budgetXaf` INT NULL,
  `notes` TEXT NULL,
  `enrichmentJson` TEXT NULL,
  `status` ENUM('new','contacted','quote_sent','confirmed','completed','cancelled') NOT NULL DEFAULT 'new',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tourism_service_requests_reference_unique` (`reference`),
  KEY `idx_tourism_service_requests_status_created` (`status`,`createdAt`)
);
