import { GoogleGenerativeAI } from "@google/generative-ai";

export type GeminiEvaluationDraftInput = { destinationCountry: string; projectType: "travail" | "etudes" | "tourisme"; nationality?: string; age?: number; sector?: string; yearsOfExperience?: number; educationLevel?: string; languages?: string; financialGuarantee?: string; countryDetails: Record<string, string | number | boolean | undefined> };
export type GeminiEvaluationDraft = { summary: string; strengths: string[]; gapsToClarify: string[]; documentPriorities: string[]; advisorQuestions: string[]; humanReviewRequired: true; disclaimer: string };
const DISCLAIMER = "Brouillon d’orientation interne fondé uniquement sur les réponses déclarées. Il ne constitue ni une décision, ni un avis juridique, ni une confirmation d’éligibilité, de visa, d’admission ou d’emploi. Une validation humaine et les sources officielles restent obligatoires.";

export function buildGeminiEvaluationPrompt(input: GeminiEvaluationDraftInput): string { return `Tu prépares un brouillon interne d’orientation pour un conseiller de mobilité internationale. Tu ne dois utiliser que les informations déclarées ci-dessous. N’invente aucune règle, aucun seuil, aucune exigence officielle, aucun fait de marché ni aucune source. Ne conclus jamais à l’éligibilité, à l’inéligibilité, à l’obtention d’un visa, d’une admission ou d’un emploi. Signale les informations manquantes et les éléments à vérifier sur les sources officielles.\n\nRéponds UNIQUEMENT en JSON valide avec les clés summary (string, 600 caractères max), strengths (array max 4), gapsToClarify (array max 6), documentPriorities (array max 6), advisorQuestions (array max 5), humanReviewRequired (true), disclaimer (string). Utilise le français.\n\nDonnées déclarées :\n${JSON.stringify(input)}`; }
function normalizeDraft(value: unknown): GeminiEvaluationDraft { const record = (value && typeof value === "object" ? value : {}) as Record<string, unknown>; const list = (key: string, limit: number) => Array.isArray(record[key]) ? record[key].filter((entry): entry is string => typeof entry === "string").map((entry) => entry.trim()).filter(Boolean).slice(0, limit) : []; return { summary: typeof record.summary === "string" ? record.summary.trim().slice(0, 600) : "Informations à examiner par un conseiller.", strengths: list("strengths", 4), gapsToClarify: list("gapsToClarify", 6), documentPriorities: list("documentPriorities", 6), advisorQuestions: list("advisorQuestions", 5), humanReviewRequired: true, disclaimer: DISCLAIMER }; }
export async function generateGeminiEvaluationDraft(input: GeminiEvaluationDraftInput, apiKey = process.env.GEMINI_API_KEY): Promise<GeminiEvaluationDraft> { if (!apiKey) throw new Error("Configuration Gemini indisponible."); const client = new GoogleGenerativeAI(apiKey); const model = client.getGenerativeModel({ model: "gemini-3.6-flash", generationConfig: { temperature: 0.1, responseMimeType: "application/json" } }); const response = await model.generateContent(buildGeminiEvaluationPrompt(input)); try { return normalizeDraft(JSON.parse(response.response.text())); } catch { return normalizeDraft({ summary: response.response.text() }); } }
