const escapeXml = (value: string) => value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;" })[char] ?? char);

export function renderOgImageSvg(title: string, path = "/") {
  const safeTitle = escapeXml(title.trim().slice(0, 96) || "3M Travel Agency");
  const safePath = escapeXml(path.trim().slice(0, 80) || "/");
  const titleLines = safeTitle.match(/.{1,42}(?:\s|$)/g)?.map((line) => line.trim()).filter(Boolean).slice(0, 2) ?? [safeTitle];
  const titleMarkup = titleLines.map((line, index) => `<text x="96" y="${292 + index * 58}" class="title">${line}</text>`).join("");
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630" role="img" aria-labelledby="title desc"><title id="title">${safeTitle}</title><desc id="desc">Aperçu officiel 3M Travel &amp; Services</desc><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#06152f"/><stop offset="1" stop-color="#123f80"/></linearGradient><linearGradient id="gold" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#f4b942"/><stop offset="1" stop-color="#ffe3a0"/></linearGradient></defs><rect width="1200" height="630" fill="url(#bg)"/><circle cx="1040" cy="100" r="210" fill="#f4b942" opacity=".12"/><circle cx="1040" cy="100" r="130" fill="none" stroke="#f4b942" stroke-width="2" opacity=".55"/><rect x="96" y="92" width="104" height="8" rx="4" fill="url(#gold)"/><text x="96" y="176" class="brand">3M TRAVEL &amp; SERVICES</text>${titleMarkup}<text x="96" y="474" class="path">${safePath}</text><text x="96" y="532" class="footer">Mobilité internationale · Évaluation · Accompagnement documenté</text><style>.brand{fill:#ffe3a0;font:700 24px Arial,sans-serif;letter-spacing:4px}.title{fill:#fff;font:700 52px Arial,sans-serif}.path{fill:#bfd4f5;font:400 22px Arial,sans-serif}.footer{fill:#dbe8fb;font:400 22px Arial,sans-serif}</style></svg>`;
}
