/**
 * Liste des pays du monde proposés dans les formulaires (196 : 193 États membres de l'ONU, le Vatican,
 * la Palestine et Taïwan). Source unique partagée par le serveur (validation) et le client (menus).
 *
 * Généré une fois à partir des noms français standard (Intl.DisplayNames) puis figé ici afin que le
 * client et le serveur voient exactement les mêmes libellés, quelle que soit la version d'ICU. Les
 * libellés déjà enregistrés en base par l'ancienne liste de 20 pays sont conservés à l'identique.
 * Le code ISO 3166-1 alpha-2 sert à afficher le drapeau et à identifier le pays sans ambiguïté.
 */
export type WorldCountryRow = readonly [code: string, name: string, region: string];

export const WORLD_COUNTRY_ROWS: readonly WorldCountryRow[] = [
  ["AF", "Afghanistan", "Asie"],
  ["ZA", "Afrique du Sud", "Afrique"],
  ["AL", "Albanie", "Europe"],
  ["DZ", "Algérie", "Afrique"],
  ["DE", "Allemagne", "Europe"],
  ["AD", "Andorre", "Europe"],
  ["AO", "Angola", "Afrique"],
  ["AG", "Antigua-et-Barbuda", "Amérique latine et Caraïbes"],
  ["SA", "Arabie Saoudite", "Golfe et Moyen-Orient"],
  ["AR", "Argentine", "Amérique latine et Caraïbes"],
  ["AM", "Arménie", "Asie"],
  ["AU", "Australie", "Océanie"],
  ["AT", "Autriche", "Europe"],
  ["AZ", "Azerbaïdjan", "Asie"],
  ["BS", "Bahamas", "Amérique latine et Caraïbes"],
  ["BH", "Bahreïn", "Golfe et Moyen-Orient"],
  ["BD", "Bangladesh", "Asie"],
  ["BB", "Barbade", "Amérique latine et Caraïbes"],
  ["BE", "Belgique", "Europe"],
  ["BZ", "Belize", "Amérique latine et Caraïbes"],
  ["BJ", "Bénin", "Afrique"],
  ["BT", "Bhoutan", "Asie"],
  ["BY", "Biélorussie", "Europe"],
  ["BO", "Bolivie", "Amérique latine et Caraïbes"],
  ["BA", "Bosnie-Herzégovine", "Europe"],
  ["BW", "Botswana", "Afrique"],
  ["BR", "Brésil", "Amérique latine et Caraïbes"],
  ["BN", "Brunei", "Asie"],
  ["BG", "Bulgarie", "Europe"],
  ["BF", "Burkina Faso", "Afrique"],
  ["BI", "Burundi", "Afrique"],
  ["KH", "Cambodge", "Asie"],
  ["CM", "Cameroun", "Afrique"],
  ["CA", "Canada", "Amérique du Nord"],
  ["CV", "Cap-Vert", "Afrique"],
  ["CL", "Chili", "Amérique latine et Caraïbes"],
  ["CN", "Chine", "Asie"],
  ["CY", "Chypre", "Europe"],
  ["CO", "Colombie", "Amérique latine et Caraïbes"],
  ["KM", "Comores", "Afrique"],
  ["CG", "Congo-Brazzaville", "Afrique"],
  ["CD", "Congo-Kinshasa", "Afrique"],
  ["KP", "Corée du Nord", "Asie"],
  ["KR", "Corée du Sud", "Asie"],
  ["CR", "Costa Rica", "Amérique latine et Caraïbes"],
  ["CI", "Côte d’Ivoire", "Afrique"],
  ["HR", "Croatie", "Europe"],
  ["CU", "Cuba", "Amérique latine et Caraïbes"],
  ["DK", "Danemark", "Europe"],
  ["DJ", "Djibouti", "Afrique"],
  ["DM", "Dominique", "Amérique latine et Caraïbes"],
  ["EG", "Égypte", "Afrique"],
  ["AE", "Émirats Arabes Unis", "Golfe et Moyen-Orient"],
  ["EC", "Équateur", "Amérique latine et Caraïbes"],
  ["ER", "Érythrée", "Afrique"],
  ["ES", "Espagne", "Europe"],
  ["EE", "Estonie", "Europe"],
  ["SZ", "Eswatini", "Afrique"],
  ["US", "États-Unis", "Amérique du Nord"],
  ["ET", "Éthiopie", "Afrique"],
  ["FJ", "Fidji", "Océanie"],
  ["FI", "Finlande", "Europe"],
  ["FR", "France", "Europe"],
  ["GA", "Gabon", "Afrique"],
  ["GM", "Gambie", "Afrique"],
  ["GE", "Géorgie", "Asie"],
  ["GH", "Ghana", "Afrique"],
  ["GR", "Grèce", "Europe"],
  ["GD", "Grenade", "Amérique latine et Caraïbes"],
  ["GT", "Guatemala", "Amérique latine et Caraïbes"],
  ["GN", "Guinée", "Afrique"],
  ["GQ", "Guinée équatoriale", "Afrique"],
  ["GW", "Guinée-Bissau", "Afrique"],
  ["GY", "Guyana", "Amérique latine et Caraïbes"],
  ["HT", "Haïti", "Amérique latine et Caraïbes"],
  ["HN", "Honduras", "Amérique latine et Caraïbes"],
  ["HU", "Hongrie", "Europe"],
  ["MH", "Îles Marshall", "Océanie"],
  ["SB", "Îles Salomon", "Océanie"],
  ["IN", "Inde", "Asie"],
  ["ID", "Indonésie", "Asie"],
  ["IQ", "Irak", "Golfe et Moyen-Orient"],
  ["IR", "Iran", "Golfe et Moyen-Orient"],
  ["IE", "Irlande", "Europe"],
  ["IS", "Islande", "Europe"],
  ["IL", "Israël", "Golfe et Moyen-Orient"],
  ["IT", "Italie", "Europe"],
  ["JM", "Jamaïque", "Amérique latine et Caraïbes"],
  ["JP", "Japon", "Asie"],
  ["JO", "Jordanie", "Golfe et Moyen-Orient"],
  ["KZ", "Kazakhstan", "Asie"],
  ["KE", "Kenya", "Afrique"],
  ["KG", "Kirghizstan", "Asie"],
  ["KI", "Kiribati", "Océanie"],
  ["KW", "Koweït", "Golfe et Moyen-Orient"],
  ["LA", "Laos", "Asie"],
  ["LS", "Lesotho", "Afrique"],
  ["LV", "Lettonie", "Europe"],
  ["LB", "Liban", "Golfe et Moyen-Orient"],
  ["LR", "Liberia", "Afrique"],
  ["LY", "Libye", "Afrique"],
  ["LI", "Liechtenstein", "Europe"],
  ["LT", "Lituanie", "Europe"],
  ["LU", "Luxembourg", "Europe"],
  ["MK", "Macédoine du Nord", "Europe"],
  ["MG", "Madagascar", "Afrique"],
  ["MY", "Malaisie", "Asie"],
  ["MW", "Malawi", "Afrique"],
  ["MV", "Maldives", "Asie"],
  ["ML", "Mali", "Afrique"],
  ["MT", "Malte", "Europe"],
  ["MA", "Maroc", "Afrique"],
  ["MU", "Maurice", "Afrique"],
  ["MR", "Mauritanie", "Afrique"],
  ["MX", "Mexique", "Amérique latine et Caraïbes"],
  ["FM", "Micronésie", "Océanie"],
  ["MD", "Moldavie", "Europe"],
  ["MC", "Monaco", "Europe"],
  ["MN", "Mongolie", "Asie"],
  ["ME", "Monténégro", "Europe"],
  ["MZ", "Mozambique", "Afrique"],
  ["MM", "Myanmar (Birmanie)", "Asie"],
  ["NA", "Namibie", "Afrique"],
  ["NR", "Nauru", "Océanie"],
  ["NP", "Népal", "Asie"],
  ["NI", "Nicaragua", "Amérique latine et Caraïbes"],
  ["NE", "Niger", "Afrique"],
  ["NG", "Nigeria", "Afrique"],
  ["NO", "Norvège", "Europe"],
  ["NZ", "Nouvelle-Zélande", "Océanie"],
  ["OM", "Oman", "Golfe et Moyen-Orient"],
  ["UG", "Ouganda", "Afrique"],
  ["UZ", "Ouzbékistan", "Asie"],
  ["PK", "Pakistan", "Asie"],
  ["PW", "Palaos", "Océanie"],
  ["PS", "Palestine", "Golfe et Moyen-Orient"],
  ["PA", "Panama", "Amérique latine et Caraïbes"],
  ["PG", "Papouasie-Nouvelle-Guinée", "Océanie"],
  ["PY", "Paraguay", "Amérique latine et Caraïbes"],
  ["NL", "Pays-Bas", "Europe"],
  ["PE", "Pérou", "Amérique latine et Caraïbes"],
  ["PH", "Philippines", "Asie"],
  ["PL", "Pologne", "Europe"],
  ["PT", "Portugal", "Europe"],
  ["QA", "Qatar", "Golfe et Moyen-Orient"],
  ["CF", "République centrafricaine", "Afrique"],
  ["DO", "République dominicaine", "Amérique latine et Caraïbes"],
  ["RO", "Roumanie", "Europe"],
  ["GB", "Royaume-Uni", "Europe"],
  ["RU", "Russie", "Europe"],
  ["RW", "Rwanda", "Afrique"],
  ["KN", "Saint-Christophe-et-Niévès", "Amérique latine et Caraïbes"],
  ["SM", "Saint-Marin", "Europe"],
  ["VC", "Saint-Vincent-et-les Grenadines", "Amérique latine et Caraïbes"],
  ["LC", "Sainte-Lucie", "Amérique latine et Caraïbes"],
  ["SV", "Salvador", "Amérique latine et Caraïbes"],
  ["WS", "Samoa", "Océanie"],
  ["ST", "Sao Tomé-et-Principe", "Afrique"],
  ["SN", "Sénégal", "Afrique"],
  ["RS", "Serbie", "Europe"],
  ["SC", "Seychelles", "Afrique"],
  ["SL", "Sierra Leone", "Afrique"],
  ["SG", "Singapour", "Asie"],
  ["SK", "Slovaquie", "Europe"],
  ["SI", "Slovénie", "Europe"],
  ["SO", "Somalie", "Afrique"],
  ["SD", "Soudan", "Afrique"],
  ["SS", "Soudan du Sud", "Afrique"],
  ["LK", "Sri Lanka", "Asie"],
  ["SE", "Suède", "Europe"],
  ["CH", "Suisse", "Europe"],
  ["SR", "Suriname", "Amérique latine et Caraïbes"],
  ["SY", "Syrie", "Golfe et Moyen-Orient"],
  ["TJ", "Tadjikistan", "Asie"],
  ["TW", "Taïwan", "Asie"],
  ["TZ", "Tanzanie", "Afrique"],
  ["TD", "Tchad", "Afrique"],
  ["CZ", "Tchéquie", "Europe"],
  ["TH", "Thaïlande", "Asie"],
  ["TL", "Timor oriental", "Asie"],
  ["TG", "Togo", "Afrique"],
  ["TO", "Tonga", "Océanie"],
  ["TT", "Trinité-et-Tobago", "Amérique latine et Caraïbes"],
  ["TN", "Tunisie", "Afrique"],
  ["TM", "Turkménistan", "Asie"],
  ["TR", "Turquie", "Golfe et Moyen-Orient"],
  ["TV", "Tuvalu", "Océanie"],
  ["UA", "Ukraine", "Europe"],
  ["UY", "Uruguay", "Amérique latine et Caraïbes"],
  ["VU", "Vanuatu", "Océanie"],
  ["VA", "Vatican", "Europe"],
  ["VE", "Venezuela", "Amérique latine et Caraïbes"],
  ["VN", "Viêt Nam", "Asie"],
  ["YE", "Yémen", "Golfe et Moyen-Orient"],
  ["ZM", "Zambie", "Afrique"],
  ["ZW", "Zimbabwe", "Afrique"],
];

/**
 * Pays pour lesquels le site dispose d'un parcours avec source officielle vérifiée
 * (shared/candidateJourneyCatalog + officialSourceCatalog). Un test contrôle qu'aucun pays de cette
 * liste ne perd sa source : on ne promet jamais un « guide complet » qui n'existe pas.
 */
export const GUIDE_COUNTRY_CODES: readonly string[] = ["ZA","DZ","DE","AR","AU","AT","BE","BR","BG","CA","CL","CO","KR","HR","DK","AE","ES","EE","US","ET","FI","FR","GH","GR","IN","IE","JP","KE","LV","LT","LU","MA","MU","MX","NG","NO","NZ","UG","NL","PE","PL","PT","RO","GB","RW","RS","SK","SI","SE","CH","TZ","TN","UA"];
