import { useMemo, useState } from "react";
import { BriefcaseBusiness, Building2, Eye, FilePlus2, RefreshCw, Send, ShieldCheck, UserRoundCheck } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

type Props = { sessionToken: string };
const submissionLabels: Record<string, string> = { submitted: "Soumis", under_review: "En revue", shortlisted: "Présélectionné", selected: "Sélectionné", not_selected: "Non retenu", documents_requested: "Pièces demandées", procedure_ready: "Procédure à ouvrir", withdrawn: "Retiré" };

export function AdminPlacementPipeline({ sessionToken }: Props) {
  const utils = trpc.useUtils();
  const [org, setOrg] = useState({ legalName: "", country: "", contactEmail: "", organizationType: "employer" as "employer" | "placement_partner", verified: false });
  const [employerAccess, setEmployerAccess] = useState({ organizationId: "", fullName: "", email: "" });
  const [issuedAccess, setIssuedAccess] = useState<{ email: string; temporaryPassword: string } | null>(null);
  const [profile, setProfile] = useState({ candidateId: "", summary: "", targetDestination: "", targetProcedure: "", sector: "", yearsExperience: "", languagesSummary: "" });
  const [submission, setSubmission] = useState({ profileId: "", organizationId: "", adminNote: "" });
  const listQuery = trpc.placementPortal.adminList.useQuery({ sessionToken }, { enabled: Boolean(sessionToken) });
  const refresh = () => void utils.placementPortal.adminList.invalidate({ sessionToken });
  const organizationMutation = trpc.placementPortal.adminCreateOrganization.useMutation({ onSuccess: () => { toast.success("Organisation enregistrée", { description: "Elle ne reçoit aucun profil tant qu’elle n’est pas vérifiée." }); setOrg({ legalName: "", country: "", contactEmail: "", organizationType: "employer", verified: false }); refresh(); }, onError: (error) => toast.error(error.message) });
  const profileMutation = trpc.placementPortal.adminCreateProfile.useMutation({ onSuccess: () => { toast.success("Profil anonymisé préparé"); setProfile({ candidateId: "", summary: "", targetDestination: "", targetProcedure: "", sector: "", yearsExperience: "", languagesSummary: "" }); refresh(); }, onError: (error) => toast.error("Profil non créé", { description: error.message }) });
  const submissionMutation = trpc.placementPortal.adminSubmitProfile.useMutation({ onSuccess: () => { toast.success("Profil soumis", { description: "La soumission est journalisée. Aucun candidat n’est notifié automatiquement." }); setSubmission({ profileId: "", organizationId: "", adminNote: "" }); refresh(); }, onError: (error) => toast.error("Soumission impossible", { description: error.message }) });
  const employerAccessMutation = trpc.placementPortal.adminCreateEmployerAccess.useMutation({ onSuccess: (result) => { setIssuedAccess({ email: employerAccess.email, temporaryPassword: result.temporaryPassword }); setEmployerAccess({ organizationId: "", fullName: "", email: "" }); toast.success("Accès employeur généré", { description: "Remettez-le manuellement après vérification de l’organisation." }); }, onError: (error) => toast.error("Accès non créé", { description: error.message }) });
  const organizations = listQuery.data?.organizations ?? [];
  const profiles = listQuery.data?.profiles ?? [];
  const submissions = listQuery.data?.submissions ?? [];
  const verifiedOrganizations = useMemo(() => organizations.filter((row) => row.verificationStatus === "verified"), [organizations]);

  return <section className="rounded-2xl border border-indigo-200 bg-gradient-to-br from-indigo-50 to-white p-4 shadow-sm" aria-label="Pilotage de placement international">
    <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><h2 className="flex items-center gap-2 font-black text-slate-950"><BriefcaseBusiness className="h-5 w-5 text-indigo-700" />Pilotage de placement international</h2><p className="mt-1 max-w-3xl text-sm text-slate-600">Préparez des profils anonymisés après consentement, soumettez-les à des organisations vérifiées et examinez tout retour avant la procédure.</p></div><Button variant="outline" size="sm" onClick={refresh} disabled={listQuery.isFetching} className="gap-2"><RefreshCw className={`h-4 w-4 ${listQuery.isFetching ? "animate-spin" : ""}`} />Actualiser</Button></div>
    <div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-indigo-100 bg-white p-3"><p className="text-xs font-bold uppercase text-indigo-700">Organisations</p><p className="mt-1 text-2xl font-black text-indigo-950">{organizations.length}</p><p className="text-xs text-slate-500">{verifiedOrganizations.length} vérifiée(s)</p></div><div className="rounded-xl border border-sky-100 bg-white p-3"><p className="text-xs font-bold uppercase text-sky-700">Profils anonymisés</p><p className="mt-1 text-2xl font-black text-sky-950">{profiles.length}</p><p className="text-xs text-slate-500">Consentement candidat requis</p></div><div className="rounded-xl border border-emerald-100 bg-white p-3"><p className="text-xs font-bold uppercase text-emerald-700">Retours à examiner</p><p className="mt-1 text-2xl font-black text-emerald-950">{submissions.filter((row) => ["shortlisted", "selected", "documents_requested"].includes(row.status)).length}</p><p className="text-xs text-slate-500">Décision humaine obligatoire</p></div></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3">
      <Card className="border-indigo-100"><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><Building2 className="h-4 w-4 text-indigo-700" />Organisation partenaire</CardTitle><CardDescription>Créez l’organisation, puis confirmez sa vérification.</CardDescription></CardHeader><CardContent className="space-y-2"><Input value={org.legalName} onChange={(event) => setOrg({ ...org, legalName: event.target.value })} placeholder="Raison sociale" /><Input value={org.country} onChange={(event) => setOrg({ ...org, country: event.target.value })} placeholder="Pays" /><Input value={org.contactEmail} onChange={(event) => setOrg({ ...org, contactEmail: event.target.value })} placeholder="E-mail professionnel" type="email" /><Select value={org.organizationType} onValueChange={(value) => setOrg({ ...org, organizationType: value as "employer" | "placement_partner" })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="employer">Employeur</SelectItem><SelectItem value="placement_partner">Agence de placement</SelectItem></SelectContent></Select><label className="flex gap-2 text-xs text-slate-700"><input type="checkbox" checked={org.verified} onChange={(event) => setOrg({ ...org, verified: event.target.checked })} />J’ai vérifié cette organisation avant son activation.</label><Button className="w-full bg-indigo-700 hover:bg-indigo-800" disabled={organizationMutation.isPending || !org.legalName || !org.country || !org.contactEmail} onClick={() => organizationMutation.mutate({ sessionToken, ...org })}>{organizationMutation.isPending ? "Enregistrement…" : "Enregistrer l’organisation"}</Button></CardContent></Card>
      <Card className="border-sky-100"><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><UserRoundCheck className="h-4 w-4 text-sky-700" />Profil autorisé</CardTitle><CardDescription>Le candidat doit avoir accordé son consentement dans son espace.</CardDescription></CardHeader><CardContent className="space-y-2"><Input value={profile.candidateId} onChange={(event) => setProfile({ ...profile, candidateId: event.target.value })} placeholder="Identifiant candidat" inputMode="numeric" /><Textarea value={profile.summary} onChange={(event) => setProfile({ ...profile, summary: event.target.value })} placeholder="Résumé professionnel anonymisé" /><Input value={profile.targetDestination} onChange={(event) => setProfile({ ...profile, targetDestination: event.target.value })} placeholder="Destination ciblée" /><Input value={profile.targetProcedure} onChange={(event) => setProfile({ ...profile, targetProcedure: event.target.value })} placeholder="Procédure" /><Input value={profile.sector} onChange={(event) => setProfile({ ...profile, sector: event.target.value })} placeholder="Secteur (facultatif)" /><Input value={profile.yearsExperience} onChange={(event) => setProfile({ ...profile, yearsExperience: event.target.value })} placeholder="Expérience (facultatif)" /><Input value={profile.languagesSummary} onChange={(event) => setProfile({ ...profile, languagesSummary: event.target.value })} placeholder="Langues (facultatif)" /><Button className="w-full bg-sky-700 hover:bg-sky-800" disabled={profileMutation.isPending || !profile.candidateId || profile.summary.length < 30 || !profile.targetDestination || !profile.targetProcedure} onClick={() => profileMutation.mutate({ sessionToken, candidateId: Number(profile.candidateId), summary: profile.summary, targetDestination: profile.targetDestination, targetProcedure: profile.targetProcedure, sector: profile.sector || undefined, yearsExperience: profile.yearsExperience || undefined, languagesSummary: profile.languagesSummary || undefined })}><FilePlus2 className="mr-2 h-4 w-4" />Préparer le profil</Button></CardContent></Card>
      <Card className="border-emerald-100"><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><Send className="h-4 w-4 text-emerald-700" />Soumission contrôlée</CardTitle><CardDescription>Limité aux organisations vérifiées et aux consentements actifs.</CardDescription></CardHeader><CardContent className="space-y-2"><Select value={submission.profileId} onValueChange={(value) => setSubmission({ ...submission, profileId: value })}><SelectTrigger><SelectValue placeholder="Choisir un profil" /></SelectTrigger><SelectContent>{profiles.map((row) => <SelectItem key={row.id} value={String(row.id)}>{row.profileCode} · {row.targetDestination}</SelectItem>)}</SelectContent></Select><Select value={submission.organizationId} onValueChange={(value) => setSubmission({ ...submission, organizationId: value })}><SelectTrigger><SelectValue placeholder="Organisation vérifiée" /></SelectTrigger><SelectContent>{verifiedOrganizations.map((row) => <SelectItem key={row.id} value={String(row.id)}>{row.legalName} · {row.country}</SelectItem>)}</SelectContent></Select><Textarea value={submission.adminNote} onChange={(event) => setSubmission({ ...submission, adminNote: event.target.value })} placeholder="Note interne facultative" /><Button className="w-full bg-emerald-700 hover:bg-emerald-800" disabled={submissionMutation.isPending || !submission.profileId || !submission.organizationId} onClick={() => submissionMutation.mutate({ sessionToken, profileId: Number(submission.profileId), organizationId: Number(submission.organizationId), adminNote: submission.adminNote || undefined })}><ShieldCheck className="mr-2 h-4 w-4" />Confirmer la soumission</Button></CardContent></Card>
      <Card className="border-amber-100"><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><Eye className="h-4 w-4 text-amber-700" />Accès employeur</CardTitle><CardDescription>Un mot de passe temporaire est généré une seule fois par le système.</CardDescription></CardHeader><CardContent className="space-y-2"><Select value={employerAccess.organizationId} onValueChange={(value) => setEmployerAccess({ ...employerAccess, organizationId: value })}><SelectTrigger><SelectValue placeholder="Organisation vérifiée" /></SelectTrigger><SelectContent>{verifiedOrganizations.filter((row) => row.organizationType === "employer").map((row) => <SelectItem key={row.id} value={String(row.id)}>{row.legalName}</SelectItem>)}</SelectContent></Select><Input value={employerAccess.fullName} onChange={(event) => setEmployerAccess({ ...employerAccess, fullName: event.target.value })} placeholder="Nom du contact employeur" /><Input type="email" value={employerAccess.email} onChange={(event) => setEmployerAccess({ ...employerAccess, email: event.target.value })} placeholder="E-mail professionnel" /><Button className="w-full bg-amber-700 hover:bg-amber-800" disabled={employerAccessMutation.isPending || !employerAccess.organizationId || !employerAccess.fullName || !employerAccess.email} onClick={() => employerAccessMutation.mutate({ sessionToken, organizationId: Number(employerAccess.organizationId), fullName: employerAccess.fullName, email: employerAccess.email })}>Générer l’accès vérifié</Button>{issuedAccess && <div className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-xs text-amber-950" role="alert"><p className="font-bold">Identifiants à remettre maintenant</p><p className="mt-1">{issuedAccess.email}</p><code className="mt-2 block select-all rounded bg-white p-2 font-mono text-sm">{issuedAccess.temporaryPassword}</code><p className="mt-2">Copiez-le puis remettez-le par un canal approuvé. Il ne sera plus affiché après actualisation.</p></div>}</CardContent></Card>
    </div>
    <div className="mt-4 rounded-xl border border-slate-200 bg-white p-3"><div className="flex items-center justify-between gap-3"><p className="font-bold text-slate-950">Suivis de placement récents</p><Badge className="bg-slate-100 text-slate-700">{submissions.length}</Badge></div>{submissions.length === 0 ? <p className="mt-2 text-sm text-slate-600">Aucun profil n’a encore été soumis. Préparez d’abord un profil avec consentement actif.</p> : <ul className="mt-3 space-y-2">{submissions.slice(0, 8).map((row) => <li key={row.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-slate-200 p-2 text-sm"><span>Profil #{row.profileId} · Organisation #{row.organizationId}</span><Badge variant="outline">{submissionLabels[row.status] ?? row.status}</Badge></li>)}</ul>}</div>
  </section>;
}
