import { useMemo, useState } from "react";
import { CheckCircle2, Edit3, Globe2, History, Plus, RotateCcw, Search, ShieldAlert, Sparkles, Trash2, XCircle } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { evisasDatabaseComplete } from "@/data/evisasDatabaseComplete";
import { buildSuggestedNotes, hasEvisaAiDifference } from "@/lib/evisaAiComparison";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

type ManagedEntry = {
  id?: number; slug: string; country: string; capital: string; flag: string; region: string; visaType: string; duration: string; delay: string;
  requirements: string; fee: string; notes: string; imageUrl?: string; officialPortalUrl: string; officialPortalLabel: string;
  officialVerifiedAt: string; highlights: string[]; emblems: string[]; steps: string[]; isActive: boolean;
};
type AiSuggestion = { requirements: string[]; feeSuggestion: string; delaySuggestion: string; procedureSteps: string[]; precautions: string[]; adminReviewNote: string; requiresOfficialVerification: true };

const blankEntry = (): ManagedEntry => ({ slug: "", country: "", capital: "", flag: "🏳️", region: "Afrique", visaType: "e‑Visa", duration: "À confirmer", delay: "À confirmer", requirements: "", fee: "À confirmer", notes: "", imageUrl: "", officialPortalUrl: "https://", officialPortalLabel: "Portail officiel", officialVerifiedAt: new Date().toLocaleDateString("fr-FR"), highlights: [], emblems: [], steps: ["Vérifier l’éligibilité sur le portail officiel"], isActive: true });
const splitLines = (value: string) => value.split("\n").map((item) => item.trim()).filter(Boolean);
const joinLines = (value?: string[]) => (value ?? []).join("\n");

export function AdminEvisaCatalogueManager({ sessionToken }: { sessionToken: string }) {
  const utils = trpc.useUtils();
  const [search, setSearch] = useState("");
  const [countryFilter, setCountryFilter] = useState("all");
  const [editing, setEditing] = useState<ManagedEntry | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<ManagedEntry | null>(null);
  const [aiSuggestion, setAiSuggestion] = useState<AiSuggestion | null>(null);
  const [restoreTarget, setRestoreTarget] = useState<any | null>(null);
  const { data: managed = [], isLoading } = trpc.evisaCatalogue.listAdmin.useQuery({ sessionToken, includeInactive: true }, { enabled: Boolean(sessionToken) });
  const { data: auditEntries = [], isLoading: auditLoading } = trpc.evisaCatalogue.listAudit.useQuery({ sessionToken, limit: 20 }, { enabled: Boolean(sessionToken) });
  const upsert = trpc.evisaCatalogue.upsert.useMutation({ onSuccess: async () => { await utils.evisaCatalogue.listAdmin.invalidate(); await utils.evisaCatalogue.getPublicOverrides.invalidate(); setEditing(null); setAiSuggestion(null); toast.success("Catalogue e‑Visa enregistré"); }, onError: (error) => toast.error("Enregistrement impossible", { description: error.message }) });
  const setActive = trpc.evisaCatalogue.setActive.useMutation({ onSuccess: async () => { await utils.evisaCatalogue.listAdmin.invalidate(); await utils.evisaCatalogue.getPublicOverrides.invalidate(); toast.success("Visibilité de la destination mise à jour"); }, onError: (error) => toast.error("Action impossible", { description: error.message }) });
  const remove = trpc.evisaCatalogue.delete.useMutation({ onSuccess: async () => { await utils.evisaCatalogue.listAdmin.invalidate(); await utils.evisaCatalogue.getPublicOverrides.invalidate(); setDeleteTarget(null); toast.success("Surcharge e‑Visa supprimée"); }, onError: (error) => toast.error("Suppression impossible", { description: error.message }) });
  const assist = trpc.evisaCatalogue.suggestWithAI.useMutation({ onSuccess: (suggestion) => { setAiSuggestion(suggestion as AiSuggestion); toast.success("Brouillon IA prêt", { description: "Comparez les modifications avant de les appliquer." }); }, onError: (error) => toast.error("Assistance IA indisponible", { description: error.message }) });
  const restore = trpc.evisaCatalogue.restoreVersion.useMutation({ onSuccess: async () => { await utils.evisaCatalogue.listAdmin.invalidate(); await utils.evisaCatalogue.listAudit.invalidate(); await utils.evisaCatalogue.getPublicOverrides.invalidate(); setRestoreTarget(null); toast.success("Version précédente restaurée", { description: "La restauration a été inscrite dans l’historique e‑Visa." }); }, onError: (error) => toast.error("Restauration impossible", { description: error.message }) });

  const merged = useMemo(() => {
    const bySlug = new Map(managed.map((item: any) => [item.slug, item]));
    const standards = evisasDatabaseComplete.map((entry) => {
      const override: any = bySlug.get(entry.id);
      return override ? override : { ...entry, slug: entry.id, visaType: entry.type, requirements: entry.docs, notes: entry.note, imageUrl: entry.image, highlights: entry.highlights, emblems: entry.emblems, steps: entry.steps, isActive: true };
    });
    const customs = managed.filter((item: any) => !evisasDatabaseComplete.some((entry) => entry.id === item.slug));
    return [...standards, ...customs] as ManagedEntry[];
  }, [managed]);
  const countries = useMemo(() => Array.from(new Set(merged.map((item) => item.country).filter(Boolean))).sort((a, b) => a.localeCompare(b, "fr")), [merged]);
  const visible = merged.filter((item) => {
    const searchMatch = `${item.country} ${item.region} ${item.requirements}`.toLowerCase().includes(search.toLowerCase());
    return searchMatch && (countryFilter === "all" || item.country === countryFilter);
  });
  const save = () => editing && upsert.mutate({ sessionToken, destination: editing });
  const requestSuggestion = () => {
    if (!editing) return;
    setAiSuggestion(null);
    assist.mutate({ sessionToken, country: editing.country, region: editing.region, visaType: editing.visaType, officialPortalUrl: editing.officialPortalUrl, officialVerifiedAt: editing.officialVerifiedAt, currentRequirements: editing.requirements, currentFee: editing.fee, currentDelay: editing.delay, currentNotes: editing.notes });
  };
  const applySuggestion = () => {
    if (!editing || !aiSuggestion) return;
    setEditing({ ...editing, requirements: aiSuggestion.requirements.join("\n"), fee: aiSuggestion.feeSuggestion, delay: aiSuggestion.delaySuggestion, steps: aiSuggestion.procedureSteps, notes: buildSuggestedNotes(editing.notes, aiSuggestion.precautions) });
    setAiSuggestion(null);
    toast.success("Toutes les propositions ont été appliquées au brouillon", { description: "Aucun changement n’est enregistré automatiquement." });
  };
  const applySuggestionField = (field: "requirements" | "fee" | "delay" | "steps" | "notes") => {
    if (!editing || !aiSuggestion) return;
    const values = { requirements: aiSuggestion.requirements.join("\n"), fee: aiSuggestion.feeSuggestion, delay: aiSuggestion.delaySuggestion, steps: aiSuggestion.procedureSteps, notes: buildSuggestedNotes(editing.notes, aiSuggestion.precautions) };
    setEditing({ ...editing, [field]: values[field] } as ManagedEntry);
    toast.success("Proposition appliquée au brouillon", { description: "Elle reste modifiable avant enregistrement." });
  };

  return <section className="space-y-5">
    <div className="flex flex-col justify-between gap-3 rounded-2xl border border-blue-100 bg-gradient-to-r from-blue-50 to-cyan-50 p-5 lg:flex-row lg:items-center"><div><h2 className="flex items-center gap-2 text-xl font-bold text-slate-900"><Globe2 className="h-5 w-5 text-blue-700" />Catalogue e‑Visa administrable</h2><p className="mt-1 max-w-3xl text-sm text-slate-600">Les exigences, le portail officiel et la date de vérification sont modifiables. Chaque mutation est réservée aux administrateurs et inscrite dans le journal d’audit.</p></div><Button onClick={() => { setEditing(blankEntry()); setAiSuggestion(null); }}><Plus className="mr-2 h-4 w-4" />Ajouter un pays</Button></div>
    <div className="flex flex-col gap-2 sm:flex-row sm:items-center"><div className="flex min-w-0 flex-1 items-center gap-2"><Search className="h-4 w-4 shrink-0 text-slate-500" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Rechercher un pays, une région ou une exigence…" className="max-w-xl" /></div><Select value={countryFilter} onValueChange={setCountryFilter}><SelectTrigger className="w-full sm:w-56"><SelectValue placeholder="Filtrer par pays" /></SelectTrigger><SelectContent><SelectItem value="all">Tous les pays</SelectItem>{countries.map((country) => <SelectItem key={country} value={country}>{country}</SelectItem>)}</SelectContent></Select><Badge variant="outline" className="w-fit">{visible.length} fiche(s)</Badge></div>
    <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[920px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-3">Pays</th><th className="p-3">Exigences</th><th className="p-3">Portail / vérification</th><th className="p-3">Statut</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{isLoading ? <tr><td className="p-6 text-slate-500" colSpan={5}>Chargement du catalogue…</td></tr> : visible.map((item) => <tr key={item.slug} className="border-t align-top"><td className="p-3"><p className="font-semibold text-slate-900">{item.flag} {item.country}</p><p className="text-xs text-slate-500">{item.region} · {item.visaType}</p></td><td className="max-w-[280px] p-3 text-xs text-slate-600">{item.requirements}</td><td className="p-3"><a className="text-xs font-medium text-blue-700 underline" href={item.officialPortalUrl} target="_blank" rel="noreferrer">{item.officialPortalLabel}</a><p className="mt-1 text-xs text-slate-500">Vérifié le {item.officialVerifiedAt}</p></td><td className="p-3">{item.isActive ? <Badge className="bg-emerald-100 text-emerald-800"><CheckCircle2 className="mr-1 h-3 w-3" />Actif</Badge> : <Badge className="bg-slate-100 text-slate-700"><XCircle className="mr-1 h-3 w-3" />Masqué</Badge>}</td><td className="p-3 text-right"><div className="flex justify-end gap-2"><Button variant="outline" size="sm" onClick={() => { setEditing({ ...item, imageUrl: item.imageUrl ?? "", highlights: item.highlights ?? [], emblems: item.emblems ?? [], steps: item.steps ?? [] }); setAiSuggestion(null); }}><Edit3 className="mr-1 h-3.5 w-3.5" />Modifier</Button>{item.id ? <><Button variant="outline" size="sm" onClick={() => setActive.mutate({ sessionToken, id: item.id!, isActive: !item.isActive })}>{item.isActive ? "Masquer" : "Réactiver"}</Button><Button variant="outline" size="sm" className="text-rose-700" onClick={() => setDeleteTarget(item)}><Trash2 className="mr-1 h-3.5 w-3.5" />Supprimer</Button></> : null}</div></td></tr>)}</tbody></table></div>

    <section className="rounded-xl border bg-white p-4"><div className="flex items-center justify-between gap-3"><div><h3 className="flex items-center gap-2 font-semibold text-slate-900"><History className="h-4 w-4 text-blue-700" />Historique des modifications</h3><p className="mt-1 text-sm text-slate-600">Sélectionnez une version antérieure pour en prévisualiser le contenu puis confirmer sa restauration.</p></div><Badge variant="outline">{auditEntries.length} événement(s)</Badge></div><div className="mt-4 divide-y">{auditLoading ? <p className="py-4 text-sm text-slate-500">Chargement de l’historique…</p> : auditEntries.length ? auditEntries.map((entry: any) => <div key={entry.id} className="flex flex-col justify-between gap-3 py-3 sm:flex-row sm:items-center"><div><p className="font-medium text-slate-900">{entry.summary}</p><p className="mt-1 text-xs text-slate-500">{entry.destinationSlug} · {entry.createdAt ? new Date(entry.createdAt).toLocaleString("fr-FR") : "Date indisponible"}</p></div>{entry.previousSnapshot ? <Button variant="outline" size="sm" onClick={() => setRestoreTarget(entry)}><RotateCcw className="mr-1 h-3.5 w-3.5" />Restaurer cette version</Button> : <Badge className="w-fit bg-slate-100 text-slate-700">Version initiale</Badge>}</div>) : <p className="py-4 text-sm text-slate-500">Aucune modification administrée n’a encore été enregistrée.</p>}</div></section>

    <Dialog open={Boolean(editing)} onOpenChange={(open) => !open && (setEditing(null), setAiSuggestion(null))}><DialogContent className="max-h-[92vh] max-w-5xl overflow-y-auto"><DialogHeader><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><DialogTitle>{editing?.id ? `Modifier ${editing.country}` : "Ajouter une destination e‑Visa"}</DialogTitle><DialogDescription>Les données seront visibles dans le catalogue administrable. Vérifiez le portail officiel et la date avant l’enregistrement.</DialogDescription></div>{editing && <Button type="button" variant="outline" disabled={assist.isPending || editing.country.trim().length < 2 || !editing.officialPortalUrl.startsWith("https://")} onClick={requestSuggestion}><Sparkles className="mr-2 h-4 w-4 text-violet-600" />{assist.isPending ? "Analyse IA…" : "Assistance IA"}</Button>}</div></DialogHeader>
      {editing && <div className="grid gap-4 py-2 md:grid-cols-2">{aiSuggestion && <AiSuggestionComparison current={editing} suggestion={aiSuggestion} onApplyAll={applySuggestion} onApplyField={applySuggestionField} />}<Field label="Identifiant stable" value={editing.slug} onChange={(slug) => setEditing({ ...editing, slug })} placeholder="ex. kenya" /><Field label="Pays" value={editing.country} onChange={(country) => setEditing({ ...editing, country })} /><Field label="Capitale" value={editing.capital} onChange={(capital) => setEditing({ ...editing, capital })} /><Field label="Drapeau" value={editing.flag} onChange={(flag) => setEditing({ ...editing, flag })} /><Field label="Région" value={editing.region} onChange={(region) => setEditing({ ...editing, region })} /><Field label="Type e‑Visa" value={editing.visaType} onChange={(visaType) => setEditing({ ...editing, visaType })} /><Field label="Durée" value={editing.duration} onChange={(duration) => setEditing({ ...editing, duration })} /><Field label="Délai indicatif" value={editing.delay} onChange={(delay) => setEditing({ ...editing, delay })} /><Field label="Frais indicatifs" value={editing.fee} onChange={(fee) => setEditing({ ...editing, fee })} /><Field label="Date de vérification" value={editing.officialVerifiedAt} onChange={(officialVerifiedAt) => setEditing({ ...editing, officialVerifiedAt })} /><div className="md:col-span-2"><Field label="Portail officiel HTTPS" value={editing.officialPortalUrl} onChange={(officialPortalUrl) => setEditing({ ...editing, officialPortalUrl })} /><Field label="Libellé du portail" value={editing.officialPortalLabel} onChange={(officialPortalLabel) => setEditing({ ...editing, officialPortalLabel })} /></div><Area label="Exigences principales" value={editing.requirements} onChange={(requirements) => setEditing({ ...editing, requirements })} /><Area label="Note et limites d’éligibilité" value={editing.notes} onChange={(notes) => setEditing({ ...editing, notes })} /><Area label="Étapes de procédure (une ligne par étape)" value={joinLines(editing.steps)} onChange={(value) => setEditing({ ...editing, steps: splitLines(value) })} /><Area label="Points clés (une ligne par élément)" value={joinLines(editing.highlights)} onChange={(value) => setEditing({ ...editing, highlights: splitLines(value) })} /><div className="md:col-span-2 flex items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><ShieldAlert className="h-4 w-4 shrink-0" />Les exigences sont informatives : ne publiez pas une éligibilité individuelle ou un délai garanti.</div></div>}
      <DialogFooter><Button variant="outline" onClick={() => { setEditing(null); setAiSuggestion(null); }}>Annuler</Button><Button disabled={upsert.isPending} onClick={save}>{upsert.isPending ? "Enregistrement…" : "Enregistrer la destination"}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(deleteTarget)} onOpenChange={(open) => !open && setDeleteTarget(null)}><DialogContent><DialogHeader><DialogTitle>Supprimer cette surcharge e‑Visa ?</DialogTitle><DialogDescription>Cette action supprime la fiche administrée. Si elle remplaçait une fiche standard, la fiche standard redeviendra visible. Les messages et instantanés déjà partagés ne sont pas modifiés.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setDeleteTarget(null)}>Annuler</Button><Button variant="destructive" disabled={remove.isPending} onClick={() => deleteTarget?.id && remove.mutate({ sessionToken, id: deleteTarget.id, confirmation: "SUPPRIMER" })}>Supprimer définitivement</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(restoreTarget)} onOpenChange={(open) => !open && setRestoreTarget(null)}><DialogContent><DialogHeader><DialogTitle>Restaurer cette version e‑Visa ?</DialogTitle><DialogDescription>La fiche actuelle sera remplacée par les données affichées ci-dessous. La restauration sera enregistrée comme une nouvelle action dans l’historique.</DialogDescription></DialogHeader>{restoreTarget?.previousSnapshot && <div className="max-h-72 overflow-y-auto rounded-lg border bg-slate-50 p-3 text-sm"><p className="font-semibold">{String(restoreTarget.previousSnapshot.country ?? restoreTarget.destinationSlug)}</p><p className="mt-2 whitespace-pre-wrap"><strong>Exigences : </strong>{String(restoreTarget.previousSnapshot.requirements ?? "Non renseignées")}</p><p className="mt-2"><strong>Frais : </strong>{String(restoreTarget.previousSnapshot.fee ?? "À confirmer")}</p><p><strong>Délai : </strong>{String(restoreTarget.previousSnapshot.delay ?? "À confirmer")}</p><p className="mt-2 text-xs text-slate-600">Portail : {String(restoreTarget.previousSnapshot.officialPortalUrl ?? "Non renseigné")}</p></div>}<DialogFooter><Button variant="outline" onClick={() => setRestoreTarget(null)}>Annuler</Button><Button disabled={restore.isPending} onClick={() => restoreTarget && restore.mutate({ sessionToken, auditId: restoreTarget.id, confirmation: "RESTAURER" })}>{restore.isPending ? "Restauration…" : "Confirmer la restauration"}</Button></DialogFooter></DialogContent></Dialog>
  </section>;
}

function AiSuggestionComparison({ current, suggestion, onApplyAll, onApplyField }: { current: ManagedEntry; suggestion: AiSuggestion; onApplyAll: () => void; onApplyField: (field: "requirements" | "fee" | "delay" | "steps" | "notes") => void }) {
  const rows = [
    { key: "requirements" as const, label: "Exigences", current: current.requirements, proposed: suggestion.requirements.join("\n") },
    { key: "fee" as const, label: "Frais indicatifs", current: current.fee, proposed: suggestion.feeSuggestion },
    { key: "delay" as const, label: "Délai indicatif", current: current.delay, proposed: suggestion.delaySuggestion },
    { key: "steps" as const, label: "Étapes de procédure", current: joinLines(current.steps), proposed: joinLines(suggestion.procedureSteps) },
    { key: "notes" as const, label: "Précautions", current: current.notes, proposed: buildSuggestedNotes(current.notes, suggestion.precautions) },
  ];
  return <div className="md:col-span-2 rounded-xl border border-violet-200 bg-violet-50 p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="flex items-center gap-2 font-semibold text-violet-950"><Sparkles className="h-4 w-4" />Comparaison avant / après IA</p><p className="mt-1 text-sm text-violet-900">{suggestion.adminReviewNote}</p></div><Button type="button" size="sm" onClick={onApplyAll}>Appliquer tout</Button></div><div className="mt-4 space-y-3">{rows.map((row) => <ComparisonRow key={row.key} label={row.label} current={row.current} proposed={row.proposed} onApply={() => onApplyField(row.key)} />)}</div><p className="mt-3 text-xs font-medium text-violet-800">Les valeurs proposées sont un brouillon IA. Vérifiez-les toujours sur le portail officiel avant enregistrement.</p></div>;
}

function ComparisonRow({ label, current, proposed, onApply }: { label: string; current: string; proposed: string; onApply: () => void }) {
  const changed = hasEvisaAiDifference(current, proposed);
  return <div className={`rounded-lg border p-3 ${changed ? "border-violet-300 bg-white" : "border-slate-200 bg-slate-50"}`}><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><p className="font-medium text-slate-900">{label}</p>{changed ? <div className="flex items-center gap-2"><Badge className="bg-violet-100 text-violet-800">Modification proposée</Badge><Button type="button" variant="outline" size="sm" onClick={onApply}>Appliquer ce champ</Button></div> : <Badge className="bg-slate-100 text-slate-700">Identique</Badge>}</div><div className="grid gap-3 text-xs md:grid-cols-2"><div><p className="mb-1 font-semibold uppercase tracking-wide text-slate-500">Avant</p><pre className="whitespace-pre-wrap rounded bg-slate-100 p-2 font-sans text-slate-700">{current || "Non renseigné"}</pre></div><div><p className="mb-1 font-semibold uppercase tracking-wide text-violet-700">Proposition IA</p><pre className="whitespace-pre-wrap rounded bg-violet-100 p-2 font-sans text-violet-950">{proposed || "Aucune proposition"}</pre></div></div></div>;
}

function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) { return <div className="space-y-1"><Label>{label}</Label><Input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></div>; }
function Area({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <div className="space-y-1 md:col-span-2"><Label>{label}</Label><Textarea value={value} onChange={(event) => onChange(event.target.value)} rows={4} /></div>; }
